### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by dragonxtek** [wildan2711/multipath#1]
What do you need to run on 127.0.0.1:8008?
I have the following issue in the ryu log:

```
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/lib/hub.py", line 77, in _launch
    return func(*args, **kwargs)
  File "/home/ryu/ryu/app/ryu_multipath.py", line 111, in measure_link
    r = get(url)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8008): Max retries exceeded with url: /metric/127.0.0.1/911.ifoutoctets/json (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff650cca0d0>: Failed to establish a new connection: [Errno 111] ECONNREFUSED',))
```

**Comment by wildan2711** [comment]
Oh yeah, sorry I used sFlow-RT to measure the link bandwidths. http://www.inmon.com/products/sFlow-RT.php
You can just run it according to the steps there, or you can just disable it by commenting line #98:
hub.spawn_after(0.1, measure_link)

**Comment by wildan2711** [comment]
If you're interested, I'll upload the white paper accompanying this.

**Comment by dragonxtek** [comment]
Please, upload it
