### ISSUE TITLE
AttributeError: 'EventSwitchLeave' object has no attribute 'dpid'

### ISSUE THREAD

**Issue by dragonxtek** [wildan2711/multipath#2]
This message appears many times in the ryu console when I create the topology:
```
ProjectController: Exception occurred during handler processing. Backtrace from offending handler [switch_leave_handler] servicing event [EventSwitchLeave] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/usr/local/lib/python2.7/dist-packages/ryu/app/ryu_multipath.py", line 435, in switch_leave_handler
    switch = event.dpid
AttributeError: 'EventSwitchLeave' object has no attribute 'dpid'
```

**Comment by wildan2711** [comment]
Yeah this is a bug I have fixed before but I've forgot to commit, check my updated code.
